### PR TITLE
[Llama + LLama2] Add model support (Closes #231)

### LINKED ISSUE #231: [Feature request] Add support for llama models
**Name of the feature**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

Adding support for the llama models: https://huggingface.co/docs/transformers/model_doc/llama2

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

The llama models, particularly llama2, are pretty popular foundation models for many modern transformers use cases. Being able to run them on node servers or even in the browser would be great! I don't think this model strays too far from the traditional text-generation pipeline (already used by gpt2, gpt-neo, and a few others) so hopefully this is a easy change to make.

**Additional context**
*Add any other context or screenshots about the feature request here.*
I can provide an onnx-converted model if needed!

### PR DESCRIPTION
**Pull request by xenova**
This PR adds support for running Llama/Llama2 models in Transformers.js. It's worth noting, however, that due to various browser/WASM/ONNX limitations, I won't be releasing converted checkpoints for the set of >7B parameter models released by Meta. Instead, I'll be testing correctness with Andrej Karpathy's [TinyLlama models](https://huggingface.co/karpathy/tinyllamas) (see his [llama2.c repo](https://github.com/karpathy/llama2.c) for more information).

## Usage
```js
import { pipeline } from '@xenova/transformers';

const generator = await pipeline("text-generation", 'Xenova/llama2.c-stories42M');

const prompt = `Alice was so tired when she got back home so she went`
const output = await generator(prompt, {
    max_new_tokens: 25,
})
console.log(output[0]);
// { generated_text: 'Alice was so tired when she got back home so she went to bed. She was so tired. She had a dream. She was so happy. She was so excited to explore the' }

```

## Models:
- https://huggingface.co/Xenova/llama2.c-stories15M
- https://huggingface.co/Xenova/llama2.c-stories42M
- https://huggingface.co/Xenova/llama2.c-stories110M

## Tests:
- Running on an i9-9900k. 
- No fancy sampling... just greedy
- Prompt (from the [TinyStories](https://arxiv.org/pdf/2305.07759.pdf) paper): `Alice was so tired when she got back home so she went`

<details><summary>Code</summary>

```js
import { pipeline } from '@xenova/transformers';

const prompt = `Alice was so tired when she got back home so she went`

const models = [
    "Xenova/llama2.c-stories15M",
    "Xenova/llama2.c-stories42M",
    "Xenova/llama2.c-stories110M",
]

const quantizations = [false, true];

for (const model of models) {
    for (const quantized of quantizations) {
        const generator = await pipeline("text-generation", model, { quantized });

        const start = performance.now();
        const { generated_text } = (await generator(prompt, {
            max_new_tokens: 25,
        }))[0];
        const duration = performance.now() - start;
        console.log('='.repeat(80));
        console.log(`Test: ${model} ${quantized ? 'quantized' : 'unquantized'}`);
        console.log(`Duration: ${duration}`);
        console.log(`Continuation: ${generated_text}`);
        console.log('='.repeat(80));

        await generator.dispose();
    }
}

```
</details>

| Model | quantized? | tokens/sec (node; browser) | Continuation |
|--------|--------|--------|--------|
| 15M | no | 88.6; 77.4 | to the day that last. She was very long. Once, but she was a bitored. She washter |
| 15M | yes | 120.3; 67.4 | to the day that last. She was to the same. She was a little girl'd'darian. She was |
| 42M | no | 66.9; 47.8 | to bed. She was so happy. She had a big surprise. She had a big smile on her face. She had |
| 42M | yes | 100.0; 35.7| to bed. She was so tired. She had a dream. She was so happy. She was so excited to explore the | 
| 110M | no | 34.4; 21.1 | to her bed. She was so excited because she was going to the park with her mom. She was wearing her new | 
| 110M | yes | 63.9; 15.7 | to her bed. She was so excited to see her mommy. Mommy and she was so excited to see her |

### CODE REVIEW

**Comment by putuoka** [comment]
Hi @xenova Can this be used for a conversational-style AI?

**Comment by xenova** [comment]
> Hi @xenova Can this be used for a conversational-style AI?

If you can find a model which runs in onnxruntime-web or onnxruntime-node, then yes. 😇

**Comment by putuoka** [comment]
> > Hi @xenova Can this be used for a conversational-style AI?
> 
> If you can find a model which runs in onnxruntime-web or onnxruntime-node, then yes. 😇

It seems the answer is no
https://huggingface.co/models?pipeline_tag=conversational&sort=downloads&search=onnx

**Comment by xenova** [comment]
Many "conversational" models, like llama2, are classified as "text-generation" on the hub (e.g., https://huggingface.co/models?pipeline_tag=text-generation&sort=downloads&search=onnx). The bigger question is whether onnxruntime can actually run the models 😅

**Comment by putuoka** [comment]
btw I tried your llama code above and got the following error:

image
```

 throw Error(`Unsupported model type: ${config.model_type}`)
                  ^

Error: Unsupported model type: llama
```

**Comment by xenova** [comment]
I don't think you're running this branch correctly. Once you've cloned the repo, you can use `npm link` to make sure this dev version is used.

**Comment by bil-ash** [comment]
[Have a look at](https://github.com/xenova/transformers.js/issues/146#issuecomment-1648854668)

Also, there is a bloom(not bloomz) 560 onnx model [available](https://huggingface.co/ingo-m/bloom-560m-onnx) . I believe the 560 m model will work on nodejs and browsers(desktop) at least

**Pull request merged**
