### PR TITLE
Add support for private/gated model access (Closes #198)

### LINKED ISSUE #198: [Feature request] Support Private Models
**Support Private Models**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

With the python libraries, you can download models and tokenizers from the hub by either providing an auth token or being logged in via `huggingface-cli login --token=....`.

Ideally transformers.js would enable the same support when a user is locally logged in and the environment has the auth token in scope.

I've tried this just now to access `meta-llama/Llama-2-13b-hf` which requires a license agreement and can only be downloaded with a token.

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

This puts model access on part with the python libraries so that private models can be accessed.

**Additional context**
*Add any other context or screenshots about the feature request here.*

### LINKED ISSUE #199: [Bug] Tokenizing with Llama 2 model freezes
**Describe the bug**
*A clear and concise description of what the bug is.*

I manually downloaded the new `meta-llama/Llama-2-7b-hf` model to my local disk and loaded it up with transformer.js tokenizer.  When trying to tokenize a very particular string, tokenization halts and spins forever.  Checking top, the node process is doing _something_ but it's not clear what.  I've let this run for at least 10 minutes and it doesn't finish.

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

```js
const breaking_string = `They wrote the following:
Momentum in your online business comes from (crystal) clarity around who you serve and how you’re going to serve them. 🤔   Over on The Art of Paid Traffic podcast today, I’m pumped to share with you an interview with one of my Accelerator Group Coaching students, Trish Taylor. 🤗                                                                                           Trish is a stylist (and former celebrity stylist at that), coach and brand style expert for business women, teaching them to own their worth and show up in an authentic and meaningful way. 🙌🏼                                                        sI asked Trish to come on the show because she’s gone through what I think is a super relatable transformation in her business -- that of working with clients 1-on-1 to now scaling her business online and creating online courses and programs. 👩🏼🏼 YOU
<200d>💻
As you’ll hear, it wasn’t until she had clarity on who exactly she serves that she was able to clearly create offers that serve this audience that she’s so passionate about.  ♀️
You\'ll also hear how she’s using a quiz and challenge launch, why I don't think she should count out webinars, the metrics she should be paying attention to when evaluating her ad campaigns, and so much more. 📊
Follow the link in my bio to give today's episode a listen and I’d love to hear from you…  are there any transformations YOU
 RE wanting to make in your business? 👇🏼                                                                                  *
. . . . . . . . .`;

export default async (argv: any) => {
  const { env, AutoTokenizer, PreTrainedTokenizer } = await eval(
    "import('@xenova/transformers')"
  );
  if (process.env.LOCAL_TRANSFORMER_PATH) {
    env.localModelPath = process.env.LOCAL_TRANSFORMER_PATH;
  }
  const pretrained = await AutoTokenizer.from_pretrained(
    "meta-llama/Llama-2-7b-hf"
  );
  const tokens = pretrained.encode(breaking_string);                                                                          console.log(tokens.length);
};
```

Pre-steps requires downloading the model locally and setting LOCAL_TRANSFORMER_PATH.

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The string should be tokenized.  The same string can be tokenized with `mosaicml/mpt-7b-8k`.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: ^2.4.1
- Browser (if applicable):
- Operating system (if applicable): MacOS
- Other: Node v18.16.0

**Additional context**
*Add any other context about the problem here.*

### PR DESCRIPTION
**Pull request by xenova**
This PR adds support for accessing private/gated models on the Hugging Face Hub by specifying a [User Access Token](https://huggingface.co/docs/hub/security-tokens) as one of your environment variables.

Closes #198 

**NOTE:** Due to the possibility of leaking access tokens to users of your website or web application, we only support accessing private/gated models from server-side environments (e.g., Node.js) that have access to the process' environment variables.

### CODE REVIEW

**Comment by jasmas** [comment]
Not every private gated model can support environment variables. 
Seems a little overly opinionated.

**Comment by xenova** [comment]
> Not every private gated model can support environment variables. Seems a little overly opinionated.

@jasmas Can you please explain what you mean by this? Provided a HF access token is the recommended way to access private/gated models on the hub.

**Comment by akowalsk** [comment]
I think what he means is that not all javascript-based backends support environment variables.  [Cloudflare Workers](https://developers.cloudflare.com/workers/) have a concept of [environment variables](https://developers.cloudflare.com/workers/configuration/environment-variables/) but they're passed as runtime arguments.  the "process" object doesn't exist, which makes it impossible to set the access token.  The code itself is still running server-side in Cloudflare's infrastructure, so there's no risk of making the token public by passing it as an argument as there would be in a browser app.

**Comment by xenova** [comment]
Gotcha 👍  Well I'm all ears to find a way to improve it :) This was just a very simple way to get it done. The main reason I was careful/restrictive, is because I do not want users accidentally leaking their credentials when bundling for the browser.

**Pull request merged**
