### PR TITLE
Fix Next.js Dockerfile HOSTNAME

### PR DESCRIPTION
**Pull request by Lian1230**
HOSTNAME localhost keep the space App waiting for the build.

### CODE REVIEW

**Comment by xenova** [comment]
Thanks for this! Looks like they recently updated their template: https://github.com/vercel/next.js/pull/54342.
Could you also update the other instance of this [here](https://github.com/xenova/transformers.js/blob/0bf6e6712faddad0f9a913d30bb168906d71ad6b/examples/semantic-image-search/Dockerfile#L62)?

**Comment by xenova** [comment]
> keep the space App waiting for the build.

Just for clarity, are you saying you're running into issues when running from Hugging Face spaces? If so, can you link to that space where it's broken? You may be missing `app_port: 3000` in the README if this is the case. If this is not related to Hugging Face spaces, then I'm happy to merge.

**Comment by Lian1230** [comment]
@xenova yes, it's in Hugging Face spaces.
`app_port` is set to `3000`, but the traffic to the container is blocked.
It's also reproducible in local, if you build and run this container, 3000 is not reachable on host.

**Comment by xenova** [comment]
That's interesting - I've been able to deploy next.js apps in the past, like this one: https://huggingface.co/spaces/Xenova/next-server-example-app. Do you have a link to it so I can check it out?

**Comment by Lian1230** [comment]
@xenova I just created one for you: https://huggingface.co/spaces/phuhui/reproduce_error
maybe it's next14:
image

**Comment by xenova** [comment]
I was able to reproduce this - thanks for reporting and fixing! Merging now :)

**Pull request merged**
