### PR TITLE
Add support for Falcon and Mistral models

### LINKED ISSUE #356: [Feature request] Support Mistral
**Support the Mistral model**

**Reason for request**
1. It is the most trending model on Hugging Face.
2. Outperforms Llama 2 13B on all benchmarks tested.
3. It's the best 7B, Apache 2.0
4. They are committed to open models

**Context**
```sh
- error Error: Unsupported model type: mistral
    at AutoModelForQuestionAnswering.from_pretrained (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/models.js:3239:19)
```
Is there any plans to add support for it soon?

### PR DESCRIPTION
**Pull request by xenova**
Closes #356

NOTE: This only adds support for the architectures, but does not (yet) include converted checkpoints... mainly because we don't yet support the external data format (needed for >=2B models)

### CODE REVIEW

**Comment by felladrin** [comment]
Thank you, @xenova!
[Locutusque/TinyMistral-248M](https://huggingface.co/Locutusque/TinyMistral-248M) is working great!
Converted model to run on transformers.js can be found [here](https://huggingface.co/Felladrin/onnx-int8-TinyMistral-248M).

**Comment by xenova** [comment]
Amazing, thanks so much @felladrin for converting and uploading! 🤗 I'll test it out later today 💪

**Comment by xenova** [comment]
@felladrin Just tested it and it's actually a pretty good model! (even though in the original repo, it's listed as just a pretrained model and not meant for direct use).

I've made a [PR](https://huggingface.co/Felladrin/onnx-int8-TinyMistral-248M/discussions/1) to update the model card with some example code/usage, so others can play around with it too! 🤗

**Comment by allthingssecurity** [comment]
Not sure what i am doing wrong but I get this error

When trying with nodejs on my machine, I keep getting this error. I have used the pipeline code you gave .
Anything wrong I am doing?
Error: File not found. Could not locate "Felladrin/onnx-int8-TinyMistral-248M/config.json".
at getModelFile (C:\shashank\node_modules@xenova\transformers\src\utils.js:244:23)
at async fetchJSON (C:\shashank\node_modules@xenova\transformers\src\utils.js:297:18)
at async Promise.all (index 0)
at async AutoModelForCausalLM.from_pretrained (C:\shashank\node_modules@xenova\transformers\src\models.js:2356:33)
at async generateText (C:\shashank\edgellm\genText.js:5:19)

Here is the code
const { pipeline } = require('@xenova/transformers');

async function generateText() {
const generator = await pipeline('text-generation', 'Felladrin/onnx-int8-TinyMistral-248M');
const output = await generator('Once upon a time,', { add_special_tokens: true, max_new_tokens: 60, repetition_penalty: 1.2 });
console.log(output);
}

generateText();

I save this as js file and run via node

**Comment by felladrin** [comment]
Hey @allthingssecurity,

Could it be because the repository name was changed? Could you please try with `pipeline('text-generation', 'Felladrin/onnx-TinyMistral-248M')`?

I tested on the browser and the code is working fine, even with the outdated repo name. Maybe Node.js is not following redirections?

**Comment by felladrin** [comment]
Hi @allthingssecurity,

I just tested it on Node.js (with _.mjs_ file extension) and it worked:

image

Could you try using .mjs?

**Pull request merged**
