### PR TITLE
[DO NOT MERGE] Code example for testing ORT-Web WebNN EP

### PR DESCRIPTION
**Pull request by Honry**
This is a very rough example to enable WebNN in transformer.js. I just add some hard codes to make the "Image classification w/ google/vite-base-patch16-224" fp32 model work with ORT Web WebNN EP.
    
WebNN EP was released in onnxruntime-web dev channel started from 1.18.0-dev.20240126, so this PR depends on Guenther's https://github.com/xenova/transformers.js/pull/596 to make transformers.js work with latest ORT Web.

Please note WebNN DirectML backend is only available on Win 11 with latest Chrome Canary or Edge Canary behind "Enables WebNN API" flag.

### CODE REVIEW

**Comment by sansmoraxz** [comment]
WebNN support is out on ort.

[v1.17.3](https://github.com/microsoft/onnxruntime/releases/tag/v1.17.3)

Also chrome and edge are shipping with the API available in the `chrome://flags`.

**Comment by Honry** [comment]
> WebNN support is out on ort.
> 
> [v1.17.3](https://github.com/microsoft/onnxruntime/releases/tag/v1.17.3)
> 
> Also chrome and edge are shipping with the API available in the `chrome://flags`.

Yeah, WebNN has been released in [1.18.0](https://www.npmjs.com/package/onnxruntime-web/v/1.18.0), and enabled behind Chrome flag: "Enables WebNN API".

This is very early experimental to explore WebNN integration in transformers.js.

**Comment by xenova** [comment]
Great news! Thanks @Honry. Transformers.js v3 will use onnxruntime-web >= 1.18.0, so all updates should be made to the [v3](https://github.com/xenova/transformers.js/tree/v3) branch ([PR](https://github.com/xenova/transformers.js/pull/545)). I'll close this draft PR, but will reference it in v3 as well as for the PR which eventually adds WebNN support.

**Comment by Honry** [comment]
@xenova thank you for adding WebNN support to v3 plan, it's truly thrilling! Please feel free to reach out if there's anything we can support.

**Pull request closed without merging**
